name: AndroidX

# Controls when the action will run. 
on:
  workflow_run:
    workflows: ["AndroidX Presubmits", "CI"]
    types: [completed]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    if: ${{ false }}
    name: A job to say hello
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: "params"
        run: echo ${{ env.GITHUB_WORKSPACE }}
      - name: "prepare dir"
        run: echo "::set-output name=output-dir::$(readlink -f .)/outputs"
        id: dirs
      - id: foo
        uses: androidX/androidx-ci-action@yigit/pr-status-2-test
        with:
          run-id: ${{ github.event.workflow_run.id }}
          gcp-token: ${{ secrets.GCP_SA_KEY }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          output-folder: ${{ steps.dirs.outputs.output-dir }}
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: outputs
          path: ${{ steps.dirs.outputs.output-dir }}
