name: AndroidX

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ androidx-action-playground ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - id: foo
        uses: androidX/androidx-ci-action@yigit/action-1
        with:
          missing-param: 'foo'
