name: Invokes other

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  checkout:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello, world!

  callother:
    uses: ./.github/workflows/sub-workflow-1.yml
    with:
      project: ${{ matrix.project }}
      project-root: ${{ matrix.project-root }}
      os: ${{ matrix.custom-os || matrix.os }}
  callcomposite:
    steps:
      - uses: ./.github/actions/action1
      with:
        who-to-greet: 'hello'
