name: Update Prebuilts
on:
  workflow_dispatch:
    inputs:
      target-branch:
        description: 'The target branch for the prebuilts update'
        required: false
        default: 'main'
        type: string
      comment:
        description: 'Any comment you would like to add to the PR body'
        required: false
        default: ''
        type: string
jobs:
#   dump:
#     runs-on: ubuntu-latest
#     steps:
#       -
#         name: Dump context
#         uses: crazy-max/ghaction-dump-context@v1
  update-prebuilts:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout androidx repo"
        uses: actions/checkout@v2
      - name: "write something"
        shell: bash
        run: |
          set -x
          echo ${{ github.event }}
          echo "hello" > auto.txt
      - name: "see if anything changed"
        shell: bash
        id: "check-for-changes"
        run: |
          set -x
          git status
          HAS_CHANGES=`git status --porcelain|grep auto.txt|wc -l`
          echo "::set-output name=has_changes::$HAS_CHANGES"
      - name: "prepare commit message"
        uses: actions/github-script@v6
        id: prepare-commit-message
        with:
          script: |
            console.log(context);
            console.log(context.payload);
            [
            'Update Prebuilts for Playground',
            'This workflow was triggered by ${{ github.event.sender.login }}.',
            context.payload.event.inputs.comment,
            'Bug: n/a',
            'Test: CI',
            ].join('\n')
      - name: "we have changes"
        shell: bash
        id: "create-commit"
        if: ${{ steps.check-for-changes.outputs.has_changes >= 1 }}
        run: |
          set -x
          BRANCH_NAME="ci-workflow/update-prebuilts-${{ github.run_id }}-${{ github.run_number }}"
          git config user.email "bot@androidx.dev"
          git config user.name "AndroidX Github Bot"
          git checkout -b $BRANCH_NAME
          git add auto.txt
          git commit -m "${steps.prepare-commit-message.outputs.result}"
          git push origin $BRANCH_NAME
          # escape multi line commit message
          # https://github.community/t/set-output-truncates-multiline-strings/16852/5
          echo "::set-output name=branch-name::$BRANCH_NAME"
      - name: Create Pull Request
        if: ${{ steps.check-for-changes.outputs.has_changes >= 1 }}
        uses: actions/github-script@v6
        with:
          script: |
            const { repo, owner } = context.repo;
            const result = await github.rest.pulls.create({
              title: 'Update Prebuilts',
              owner,
              repo,
              head: '${{ steps.create-commit.outputs.branch-name }}',
              base: '${{ github.event.inputs.target-branch}}',
              body: steps.prepare-commit-message.outputs.result
            });
