name: On Workflow Run
on:
  workflow_run:
    workflows: ["CI"]
jobs:
  log:
    runs-on: ubuntu-latest
    name: "Workflow Run"
    steps:
      - name: "Setup global constants"
        id: global-constants
        run: |
          set -x
          cat $GITHUB_EVENT_PATH
